[colors.primary]
background = "0x0d1117"
foreground = "0xc9d1d9"

[colors.cursor]
text = "0x0d1117"
cursor = "0xc9d1d9"

[colors.normal]
black = "0x484f58"
red = "0xec8e2c"
green = "0x58a6ff"
yellow = "0xd29922"
blue = "0x58a6ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[colors.bright]
black = "0x6e7681"
red = "0xfdac54"
green = "0x79c0ff"
yellow = "0xe3b341"
blue = "0x79c0ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[font]
size = 9.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[scrolling]
history = 5000

[window]
opacity = 0.9
